# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wikimapia_widget.ui'
#
# Created: Tue Apr 21 11:02:15 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WikimapiaWidget(object):
    def setupUi(self, WikimapiaWidget):
        WikimapiaWidget.setObjectName(_fromUtf8("WikimapiaWidget"))
        WikimapiaWidget.resize(318, 281)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WikimapiaWidget.sizePolicy().hasHeightForWidth())
        WikimapiaWidget.setSizePolicy(sizePolicy)
        WikimapiaWidget.setFloating(False)
        WikimapiaWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.widgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetContents.sizePolicy().hasHeightForWidth())
        self.widgetContents.setSizePolicy(sizePolicy)
        self.widgetContents.setObjectName(_fromUtf8("widgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabs = QtGui.QTabWidget(self.widgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setMinimumSize(QtCore.QSize(0, 120))
        self.tabs.setTabPosition(QtGui.QTabWidget.North)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.areaTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.areaTab.sizePolicy().hasHeightForWidth())
        self.areaTab.setSizePolicy(sizePolicy)
        self.areaTab.setMinimumSize(QtCore.QSize(0, 90))
        self.areaTab.setObjectName(_fromUtf8("areaTab"))
        self.areaLayout = QtGui.QFormLayout(self.areaTab)
        self.areaLayout.setObjectName(_fromUtf8("areaLayout"))
        self.boundsLabel = QtGui.QLabel(self.areaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundsLabel.sizePolicy().hasHeightForWidth())
        self.boundsLabel.setSizePolicy(sizePolicy)
        self.boundsLabel.setObjectName(_fromUtf8("boundsLabel"))
        self.areaLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.boundsLabel)
        self.categoriesLabel = QtGui.QLabel(self.areaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoriesLabel.sizePolicy().hasHeightForWidth())
        self.categoriesLabel.setSizePolicy(sizePolicy)
        self.categoriesLabel.setObjectName(_fromUtf8("categoriesLabel"))
        self.areaLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.categoriesLabel)
        self.categoriesEdit = QtGui.QLineEdit(self.areaTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoriesEdit.sizePolicy().hasHeightForWidth())
        self.categoriesEdit.setSizePolicy(sizePolicy)
        self.categoriesEdit.setObjectName(_fromUtf8("categoriesEdit"))
        self.areaLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.categoriesEdit)
        self.boundsSelectedOnly = QtGui.QCheckBox(self.areaTab)
        self.boundsSelectedOnly.setObjectName(_fromUtf8("boundsSelectedOnly"))
        self.areaLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.boundsSelectedOnly)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.boundsCombo = QtGui.QComboBox(self.areaTab)
        self.boundsCombo.setObjectName(_fromUtf8("boundsCombo"))
        self.horizontalLayout_2.addWidget(self.boundsCombo)
        self.refreshBoundsButton = QtGui.QToolButton(self.areaTab)
        self.refreshBoundsButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/wikimapia/icons/refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshBoundsButton.setIcon(icon)
        self.refreshBoundsButton.setObjectName(_fromUtf8("refreshBoundsButton"))
        self.horizontalLayout_2.addWidget(self.refreshBoundsButton)
        self.areaLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.tabs.addTab(self.areaTab, _fromUtf8(""))
        self.idTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idTab.sizePolicy().hasHeightForWidth())
        self.idTab.setSizePolicy(sizePolicy)
        self.idTab.setObjectName(_fromUtf8("idTab"))
        self.idLayout = QtGui.QFormLayout(self.idTab)
        self.idLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.idLayout.setObjectName(_fromUtf8("idLayout"))
        self.idLabel = QtGui.QLabel(self.idTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idLabel.sizePolicy().hasHeightForWidth())
        self.idLabel.setSizePolicy(sizePolicy)
        self.idLabel.setObjectName(_fromUtf8("idLabel"))
        self.idLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.idLabel)
        self.idEdit = QtGui.QSpinBox(self.idTab)
        self.idEdit.setMaximum(999999999)
        self.idEdit.setObjectName(_fromUtf8("idEdit"))
        self.idLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.idEdit)
        self.tabs.addTab(self.idTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabs)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.destLabel = QtGui.QLabel(self.widgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destLabel.sizePolicy().hasHeightForWidth())
        self.destLabel.setSizePolicy(sizePolicy)
        self.destLabel.setObjectName(_fromUtf8("destLabel"))
        self.horizontalLayout.addWidget(self.destLabel)
        self.destCombo = QtGui.QComboBox(self.widgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destCombo.sizePolicy().hasHeightForWidth())
        self.destCombo.setSizePolicy(sizePolicy)
        self.destCombo.setMinimumSize(QtCore.QSize(153, 0))
        self.destCombo.setObjectName(_fromUtf8("destCombo"))
        self.destCombo.addItem(_fromUtf8(""))
        self.destCombo.addItem(_fromUtf8(""))
        self.destCombo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.destCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtGui.QProgressBar(self.widgetContents)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 18))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.importLayout = QtGui.QHBoxLayout()
        self.importLayout.setObjectName(_fromUtf8("importLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.importLayout.addItem(spacerItem)
        self.importButton = QtGui.QPushButton(self.widgetContents)
        self.importButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/wikimapia/icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importButton.setIcon(icon1)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.importLayout.addWidget(self.importButton)
        self.verticalLayout.addLayout(self.importLayout)
        WikimapiaWidget.setWidget(self.widgetContents)

        self.retranslateUi(WikimapiaWidget)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WikimapiaWidget)

    def retranslateUi(self, WikimapiaWidget):
        WikimapiaWidget.setWindowTitle(_translate("WikimapiaWidget", "Wikimapia", None))
        self.boundsLabel.setText(_translate("WikimapiaWidget", "boundaries", None))
        self.categoriesLabel.setText(_translate("WikimapiaWidget", "categories", None))
        self.boundsSelectedOnly.setText(_translate("WikimapiaWidget", "selected objects only", None))
        self.tabs.setTabText(self.tabs.indexOf(self.areaTab), _translate("WikimapiaWidget", "By Area", None))
        self.idLabel.setText(_translate("WikimapiaWidget", "id", None))
        self.tabs.setTabText(self.tabs.indexOf(self.idTab), _translate("WikimapiaWidget", "By ID", None))
        self.destLabel.setText(_translate("WikimapiaWidget", "target", None))
        self.destCombo.setItemText(0, _translate("WikimapiaWidget", "Wikimapia layer", None))
        self.destCombo.setItemText(1, _translate("WikimapiaWidget", "New temporary layer", None))
        self.destCombo.setItemText(2, _translate("WikimapiaWidget", "Current layer", None))
        self.importButton.setText(_translate("WikimapiaWidget", "Import", None))

import resources_rc
